# requirements.yml
---
collections:
  - name: amazon.aws
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.windows
  - name: awx.awx
  - name: community.aws
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: community.windows
  - name: kubernetes.core
  - name: https://github.com/116davinder/ansible.missing_collection.git
    type: git
    version: 0.3.0
  - name: lvrfrc87.git_acp